### ISSUE TITLE
Postal does not start up Rake error

### ISSUE THREAD

**Issue by shyim** [tiredofit/docker-postal#2]
```
09:43:58 requeuer.1         | Started with PID 1982
09:43:58 requeuer.1         | => rake aborted!
09:43:58 requeuer.1         | => LoadError: cannot load such file -- /opt/postal/config/application
09:43:58 requeuer.1         | => /opt/postal/Rakefile:4:in `require_relative'
09:43:58 requeuer.1         | => /opt/postal/Rakefile:4:in `<top (required)>'
09:43:58 requeuer.1         | => /opt/postal/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
09:43:58 requeuer.1         | => /usr/local/bundle/bin/bundle:23:in `load'
09:43:58 requeuer.1         | => /usr/local/bundle/bin/bundle:23:in `<main>'
09:43:58 requeuer.1         | => (See full trace by running task with --trace)
09:43:58 cron.1             | => rake aborted!
09:43:58 cron.1             | => LoadError: cannot load such file -- /opt/postal/config/application
09:43:58 cron.1             | => /opt/postal/Rakefile:4:in `require_relative'
09:43:58 cron.1             | => /opt/postal/Rakefile:4:in `<top (required)>'
09:43:58 cron.1             | => /opt/postal/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
09:43:58 cron.1             | => /usr/local/bundle/bin/bundle:23:in `load'
09:43:58 cron.1             | => /usr/local/bundle/bin/bundle:23:in `<main>'
09:43:58 cron.1             | => (See full trace by running task with --trace)
09:43:58 worker.1           | => script/worker.rb:2:in `require_relative': cannot load such file -- /opt/postal/config/environment (LoadError)
09:43:58 worker.1           | =>        from script/worker.rb:2:in `<main>'
09:43:58 smtp.1             | => rake aborted!
09:43:58 smtp.1             | => LoadError: cannot load such file -- /opt/postal/config/application
09:43:58 smtp.1             | => /opt/postal/Rakefile:4:in `require_relative'
09:43:58 smtp.1             | => /opt/postal/Rakefile:4:in `<top (required)>'
09:43:58 smtp.1             | => /opt/postal/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
09:43:58 smtp.1             | => /usr/local/bundle/bin/bundle:23:in `load'
09:43:58 smtp.1             | => /usr/local/bundle/bin/bundle:23:in `<main>'
09:43:58 smtp.1             | => (See full trace by running task with --trace)
09:43:58 web.1              | => bundler: failed to load command: puma (/opt/postal/vendor/bundle/ruby/2.6.0/bin/puma)
09:43:58 web.1              | => Errno::ENOENT: No such file or directory @ rb_sysopen - config/puma.rb
09:43:58 web.1              | =>   /opt/postal/vendor/bundle/ruby/2.6.0/gems/puma-4.3.1/lib/puma/dsl.rb:46:in `read'
09:43:58 web.1              | =>   /opt/postal/vendor/bundle/ruby/2.6.0/gems/puma-4.3.1/lib/puma/dsl.rb:46:in `_load_from'
09:43:58 web.1              | =>   /opt/postal/vendor/bundle/ruby/2.6.0/gems/puma-4.3.1/lib/puma/configuration.rb:195:in `block in load'
09:43:58 web.1              | =>   /opt/postal/vendor/bundle/ruby/2.6.0/gems/puma-4.3.1/lib/puma/configuration.rb:195:in `each'
09:43:58 web.1              | =>   /opt/postal/vendor/bundle/ruby/2.6.0/gems/puma-4.3.1/lib/puma/configuration.rb:195:in `load'
09:43:58 web.1              | =>   /opt/postal/vendor/bundle/ruby/2.6.0/gems/puma-4.3.1/lib/puma/launcher.rb:58:in `initialize'
09:43:58 web.1              | =>   /opt/postal/vendor/bundle/ruby/2.6.0/gems/puma-4.3.1/lib/puma/cli.rb:71:in `new'
09:43:58 web.1              | =>   /opt/postal/vendor/bundle/ruby/2.6.0/gems/puma-4.3.1/lib/puma/cli.rb:71:in `initialize'
09:43:58 web.1              | =>   /opt/postal/vendor/bundle/ruby/2.6.0/gems/puma-4.3.1/bin/puma:8:in `new'
09:43:58 web.1              | =>   /opt/postal/vendor/bundle/ruby/2.6.0/gems/puma-4.3.1/bin/puma:8:in `<top (required)>'
09:43:58 web.1              | =>   /opt/postal/vendor/bundle/ruby/2.6.0/bin/puma:23:in `load'
09:43:58 web.1              | =>   /opt/postal/vendor/bundle/ruby/2.6.0/bin/puma:23:in `<top (required)>'
```

**Comment by tiredofit** [comment]
OK, missing Puma for some reason on an automated build. To look into in a couple days, otherwise try earlier relase.

**Comment by shyim** [comment]
There is only one tag 🤔

**Comment by tiredofit** [comment]
Oh dear. Added to list on Monday after I review my production copy.
Potentially has changed on upstream so will investigate.

**Comment by shyim** [comment]
No problem. Have a good weekend 😊
